baseURL: https://book.hashbang.sh/
title: "#! Book"
languageCode: en-us
theme: book

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

enableGitInfo: true

params:
  BookRepo: https://github.com/hashbang/book
  BookEditPath: edit/master/content
